# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180118_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_markdown',
            field=models.BooleanField(default=True, verbose_name='\u4f7f\u7528markdown\u683c\u5f0f'),
        ),
    ]
